### ISSUE TITLE
Image Width

### ISSUE THREAD

**Issue by hend0298** [hend0298/columns-of-cards#1]
@thomasjbradley I put the image width to 100px like it says to but Markbot says it wants a different value for the width.

**Comment by thomasjbradley** [comment]
When we target `img` we’re targeting all possible images on the whole website—that should always be `100%`. 

But in this assignment we’re only designing a small component. We don’t want *every single image on the whole website* to be `100px` wide, only the images inside the cards. So we should so something like:

```css
.card img {
  width: 100%
}
```

**Comment by hend0298** [comment]
@thomasjbradley Okay thanks, I think I understand that. Also, why does Markbot want to see a width of 25%? Where does that go?

**Comment by thomasjbradley** [comment]
Probably on the cards, so they are all equal widths.
